# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5658346c9deecc1d0ccfcec3ee1633714ae941bca188375216ff483a661babbf9f9571d2555b8657a8815f1a0d99956b4beccefbee74d9268644dbdf113be302

test:
  secret_key_base: a1d34cfcb560d0fdfa6e2541fb39189f53d1d0baa69d802c5ffd6499f16dd0366fbf52392e29e258f8cce74f80e9fd85329ad1dcd955f10a1d98f9c44c12db00

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 247bcc1cba421694ba19274a2bba478a288ec971863812b67340ad3f506583599535e80e4f15312904101c9602ab3e17363372b9f2a26c1f1227b3326cb05144 #<%= ENV["SECRET_KEY_BASE"] %>
